### ISSUE TITLE
Error when trying to add it to my personal library on tercen.com

### ISSUE THREAD

**Issue by makostadima** [tercen/export_operator#5]
I have created a personal library team on tercen.com where I would like to create a project from Git for this operator.

The process stops halfway and I get the following error(s):

![image](https://github.com/tercen/export_operator/assets/1746464/16afdf8f-585d-49dc-8ad8-53196adb536d)

This is happening with version 0.1.7. I haven't tried earlier versions.

**Comment by tsmonteiro** [comment]
You can try either the latest non-tagged version, or 0.1.2 if I'm not mistaken. I am finishing some tests tomorrow for the new release which will fix this

**Comment by makostadima** [comment]
Unfortunately I wasn't able to load neither version on tercen.com.

Let me know when it's ready to be tested again. Thanks!

**Comment by tsmonteiro** [comment]
I have just released and tested version 0.2.0 on stage and this issue has been solved. I have not tried it on tercen.com because importing the CyTOF workflow is failing when loading scyan.

**Comment by makostadima** [comment]
I am still getting an error. Let me try to explain what I am doing:

- I have created a Team called __makostadima_personal_library__ which I have set it as a **Library Team**.
- Then I am trying to create a New project from Git (unsuccessfully) with the following details:

![image](https://github.com/tercen/export_operator/assets/1746464/7b77893d-0c56-43af-8f8b-7028f074875d)

And the error I get is this:
![image](https://github.com/tercen/export_operator/assets/1746464/39eb0da2-c7ef-4e38-93aa-0222145be9df)

Maybe I am doing something wrong? This is all on Tercen.com btw.

**Comment by tsmonteiro** [comment]
I have tried on tercen.com and it still installs the operator, though. Is this the case for you as well?

If so, could you please go ahead and try it out (I am unable to import the CyTOF workflow into tercen.com, so I am building a test workflow at the moment)? The issue you are seeing is related to the unit test (which is doing nothing, anyway) and has no bearing in the functioning of the operator.

**Comment by tsmonteiro** [comment]
Ok, I have now fully tested in in tercen.com and version 0.2.1 installs and runs.

**Comment by makostadima** [comment]
I did manage to install it!!! Hurray

Now I am trying to use it in [this workflow](https://tercen.com/Roche16AuroraPanel/w/7dc3aa350acd6547d75250cd2b6110a2/ds/ad15f974-150f-4cd1-bdf3-aa7be5f8f2d8) and I get the following error:

<img width="960" alt="image" src="https://github.com/tercen/export_operator/assets/1746464/bffbd439-4607-4a26-8141-ef472d350d2d">

My data projection is random, as I don't remember from your demo on Monday what I need to project. Can you point me to a working example, please?

**Comment by tsmonteiro** [comment]
So this was an actual code bug, which I fixed on version 2.2. I have tried it on your workflow and it is working. I will keep testing to ensure it covers all cases.

**Comment by makostadima** [comment]
Awesome! I will keep testing on different workflows too.
